academy/urls.py
from django.urls import include, path

from academy import views

urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", views.user_registration, name="signup"),
    path("terms/", views.terms, name="terms"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    path(
        "whatsapp_message/<int:contact_pk>/",
        views.whatsapp_message,
        name="whatsapp_message",
    ),
    path(
        "dancer/",
        include(
            [
                path("list/", views.dancer_list_view, name="dancer_list"),
                path("create/", views.dancer_create_view, name="dancer_create"),
                path(
                    "detail/<int:dancer_pk>/",
                    views.dancer_detail_view,
                    name="dancer_detail",
                ),
                path(
                    "update/<int:dancer_pk>/",
                    views.dancer_update_view,
                    name="dancer_update",
                ),
            ]
        ),
    ),
    path(
        "professor/",
        include(
            [
                path("list/", views.professor_list_view, name="professor_list"),
                path(
                    "create/",
                    views.professor_create_view,
                    name="professor_create",
                ),
                path(
                    "detail/<int:professor_pk>/",
                    views.professor_detail_view,
                    name="professor_detail",
                ),
                path(
                    "update/<int:professor_pk>/",
                    views.professor_update_view,
                    name="professor_update",
                ),
            ]
        ),
    ),
]

on_stage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("django.contrib.auth.urls")),
    path("", include("academy.urls")),
    path("", include("choreography.urls")),
    path("", include("seminar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

academy/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.deconstruct import deconstructible
from django.utils.translation import gettext_lazy as _


class IdentificationTypeChoices(models.TextChoices):
    ID = "ID", _("ID")
    PASSPORT = "PASSPORT", _("Passport")


def numeric_string_validator(value):
    """Validate the given string has numeric characters only."""
    if not value.isnumeric():
        raise ValidationError(_("Only numeric characters are allowed."))


@deconstructible
class MaxFileSizeValidator(object):
    def __init__(self, max_size):
        self.max_size = max_size

    def __call__(self, file):
        """Validate the given File instance size is not over the max_size set in bytes."""
        if file.size > self.max_size:
            raise ValidationError(
                _("The file you are trying to upload is over %(max_size)s MB.")
                % {"max_size": self.max_size / 1024 / 1024}
            )


def id_front_picture_path(instance, filename):
    """Given an image file and its name, return the location and a formatted file name."""
    ext = filename.split(".")[-1]
    academy_name_snaked = instance.academy.name.replace(" ", "_")
    instance_model_name = instance._meta.model.__name__
    return f"{academy_name_snaked}/{instance_model_name}/{instance.identification_number}_front.{ext}"


def id_back_picture_path(instance, filename):
    """Given an image file and its name, return the location and a formatted file name."""
    ext = filename.split(".")[-1]
    academy_name_snaked = instance.academy.name.replace(" ", "_")
    instance_model_name = instance._meta.model.__name__
    return f"{academy_name_snaked}/{instance_model_name}/{instance.identification_number}_back.{ext}"


class OSUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class OSUser(AbstractUser):
    username = None
    email = models.EmailField(verbose_name=_("email address"), unique=True)

    objects = OSUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        if all([self.first_name, self.last_name]):
            return f"{self.first_name} {self.last_name}"
        elif self.first_name:
            return self.first_name
        return self.email


class Academy(models.Model):
    """
    Store a single Academy instance, related to :model:`academy.OSUser`, :model:`academy.Professor`,
    :model:`academy.Dancer`, :model:`choreography.Choreography` and :model:`seminar.SeminarRegistration`.
    """

    user = models.OneToOneField(
        OSUser,
        models.RESTRICT,
        limit_choices_to={"is_staff": False},
        verbose_name=_("user"),
    )
    name = models.CharField(verbose_name=_("name"), max_length=50, unique=True)
    phone_number = models.CharField(
        verbose_name=_("phone number"),
        max_length=10,
        validators=[MinLengthValidator(10), numeric_string_validator],
    )
    city = models.CharField(verbose_name=_("city"), max_length=100)
    state = models.CharField(verbose_name=_("state"), max_length=100)
    create_date = models.DateTimeField(auto_now_add=True)
    change_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("academy")
        verbose_name_plural = _("academies")
        ordering = ["name"]

    def __str__(self):
        return self.name.title()

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super().save(*args, **kwargs)


class Dancer(models.Model):
    """
    Store a single Dancer instance, related to :model:`academy.Academy`, :model:`choreography.Choreography`,
    and :model:`seminar.SeminarRegistration`.
    """

    academy = models.ForeignKey(
        Academy,
        models.RESTRICT,
        related_name="dancers",
        verbose_name=_("academy"),
    )
    first_name = models.CharField(verbose_name=_("first name"), max_length=100)
    last_name = models.CharField(verbose_name=_("last name"), max_length=100)
    birth_date = models.DateField(verbose_name=_("birth date"))
    is_verified = models.BooleanField(verbose_name=_("is verified"), default=False)
    identification_type = models.CharField(
        verbose_name=_("identification type"),
        max_length=50,
        default=IdentificationTypeChoices.ID,
        choices=IdentificationTypeChoices.choices,
    )
    identification_number = models.CharField(
        verbose_name=_("identification number"), max_length=20
    )
    identification_front_image = models.ImageField(
        verbose_name=_("identification front image"),
        upload_to=id_front_picture_path,
        null=True,
        blank=True,
        validators=[MaxFileSizeValidator(10485760)],
    )
    identification_back_image = models.ImageField(
        verbose_name=_("identification back image"),
        upload_to=id_back_picture_path,
        null=True,
        blank=True,
        validators=[MaxFileSizeValidator(10485760)],
    )
    create_date = models.DateTimeField(auto_now_add=True)
    change_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("dancer")
        verbose_name_plural = _("dancers")
        ordering = ["last_name"]
        constraints = [
            models.UniqueConstraint(
                fields=["academy", "identification_type", "identification_number"],
                name="dancer_uniqueness",
            )
        ]

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

    def save(self, *args, **kwargs):
        """Title the dancer's first and last name before saving."""
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Get a string that can be used to refer to the instance detail view."""
        return reverse("dancer_detail", kwargs={"dancer_pk": self.pk})

    def get_update_url(self):
        """Get a string that can be used to refer to the instance update view."""
        return reverse("dancer_update", kwargs={"dancer_pk": self.pk})

    @property
    def age(self):
        """Calculate a dancer's age."""
        today = timezone.now().date()
        return (
            today.year
            - self.birth_date.year
            - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        )

    @property
    def id_front_image_name(self):
        return self.identification_front_image.name.split("/")[-1]

    @property
    def id_back_image_name(self):
        return self.identification_back_image.name.split("/")[-1]


class Professor(models.Model):
    """
    Store a single Professor instance, related to :model:`academy.Academy` and
    :model:`choreography.Choreography`.
    """

    academy = models.ForeignKey(
        Academy,
        models.RESTRICT,
        related_name="professors",
        verbose_name=_("academy"),
    )
    first_name = models.CharField(verbose_name=_("first name"), max_length=100)
    last_name = models.CharField(verbose_name=_("last name"), max_length=100)
    identification_type = models.CharField(
        verbose_name=_("identification type"),
        max_length=50,
        default=IdentificationTypeChoices.ID,
        choices=IdentificationTypeChoices.choices,
    )
    identification_number = models.CharField(
        verbose_name=_("identification number"), max_length=20
    )
    identification_front_image = models.ImageField(
        verbose_name=_("identification front image"),
        upload_to=id_front_picture_path,
        null=True,
        blank=True,
        validators=[MaxFileSizeValidator(10485760)],
    )
    identification_back_image = models.ImageField(
        verbose_name=_("identification back image"),
        upload_to=id_back_picture_path,
        null=True,
        blank=True,
        validators=[MaxFileSizeValidator(10485760)],
    )
    create_date = models.DateTimeField(auto_now_add=True)
    change_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("professor")
        verbose_name_plural = _("professors")
        ordering = ["last_name"]
        constraints = [
            models.UniqueConstraint(
                fields=["academy", "identification_type", "identification_number"],
                name="professor_uniqueness",
            )
        ]

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

    def save(self, *args, **kwargs):
        """Title the professor's first and last name before saving."""
        self.first_name = self.first_name.title()

academy/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import MinLengthValidator
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _

from academy.models import Academy, Dancer, Professor, numeric_string_validator

OSUser = get_user_model()


def add_class_to_label(original_function):
    """Modify required form fields HTML attributes."""

    def class_to_label_tag(self, *args, **kwargs):
        required_field = {"class": "fw-bold"}
        attrs = required_field if self.field.required else {}
        return original_function(self, attrs=attrs, label_suffix="")

    return class_to_label_tag


forms.BoundField.label_tag = add_class_to_label(forms.BoundField.label_tag)


class OSUserRegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].required = True
        self.fields["last_name"].required = True

    class Meta:
        model = OSUser
        fields = ["email", "first_name", "last_name", "password1", "password2"]

    academy_name = forms.CharField(
        max_length=50,
        label=_("Academy name"),
    )
    phone_number = forms.CharField(
        max_length=10,
        label=_("Phone number"),
        validators=[MinLengthValidator(10), numeric_string_validator],
    )
    city = forms.CharField(max_length=100, label=_("City"))
    state = forms.CharField(max_length=100, label=_("State"))
    terms = forms.BooleanField(label=_("Terms and conditions"))

    def clean(self):
        super().clean()
        academy_name = self.cleaned_data.get("academy_name")

        # Check academy name is unique.
        if Academy.objects.filter(name=academy_name.lower()).exists():
            raise ValidationError(
                {
                    "academy_name": ValidationError(
                        _(
                            "There already is a registered academy with this name: %(value)s."
                        ),
                        code="invalid",
                        params={"value": academy_name},
                    )
                }
            )


class DancerForm(forms.ModelForm):
    """
    ModelForm for creating and updating a :model:`academy.Dancer` instance.
    """

    class Meta:
        model = Dancer
        exclude = ["academy"]
        widgets = {
            "birth_date": forms.DateInput(
                format=("%Y-%m-%d"),
                attrs={
                    "class": "form-control rounded-end",
                    "type": "date",
                },
            ),
        }

    def clean(self):
        super().clean()
        identification_type = self.cleaned_data.get("identification_type")
        identification_number = self.cleaned_data.get("identification_number")

        # Check identification_type and identification_number length.
        if all(
            [identification_type, identification_type == "ID", identification_number]
        ):
            if any(
                [len(identification_number) != 8, not identification_number.isnumeric()]
            ):
                raise ValidationError(
                    {
                        "identification_number": ValidationError(
                            _("ID must have 8 numeric characters.")
                        ),
                    }
                )


class ProfessorForm(forms.ModelForm):
    """
    ModelForm for creating and updating a :model:`academy.Professor` instance.
    """

    class Meta:
        model = Professor
        exclude = ["academy"]

    def clean(self):
        super().clean()
        identification_type = self.cleaned_data.get("identification_type")
        identification_number = self.cleaned_data.get("identification_number")

        # Check identification_type and identification_number length.
        if all(
            [identification_type, identification_type == "ID", identification_number]
        ):
            if any(
                [len(identification_number) != 8, not identification_number.isnumeric()]
            ):
                raise ValidationError(
                    {
                        "identification_number": ValidationError(
                            _("ID must have 8 numeric characters.")
                        ),
                    }
                )

academy/templates/academy/dancer_detail.html
{% extends "card.html" %}
{% load static  i18n %}

{% block card_body %}

    <div class="row gx-2">
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "First name" %}</span>
                <span class="form-control">{{ object.first_name }}</span>
            </div>
        </div>
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Last name" %}</span>
                <span class="form-control">{{ object.last_name }}</span>
            </div>
        </div>
    </div>

    <div class="row gx-2">
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Birth date" %}</span>
                <span class="form-control">{{ object.birth_date|date:"SHORT_DATE_FORMAT" }}</span>
            </div>
        </div>
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Identification type" %}</span>
                <span class="form-control">{{ object.get_identification_type_display }}</span>
            </div>
        </div>
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Identification number" %}</span>
                <span class="form-control">{{ object.identification_number }}</span>
            </div>
        </div>
    </div>

    <div class="row gx-2 mb-2">
        <div class="col-sm">
            <p class="my-2">{% translate "Identification front image" %}</p>
            {% if object.identification_front_image %}
                <img src="{{ object.identification_front_image.url }}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% else %}
                <img src="{% static 'academy/images/id_card_front.svg' %}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% endif %}
        </div>
        <div class="col-sm">
            <p class="my-2">{% translate "Identification back image" %}</p>
            {% if object.identification_back_image %}
                <img src="{{ object.identification_back_image.url }}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% else %}
                <img src="{% static 'academy/images/id_card_back.svg' %}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% endif %}
        </div>
    </div>

    <div class="table-responsive mt-4">
        <table class="table table-striped align-middle text-center">
            <thead>
                <tr class="dark">
                    <td scope="col" class="align-middle">ID</td>
                    <td scope="col" class="align-middle">{% translate "Choreography name" %}</td>
                    <td scope="col" style="width: 30%;">
                        {% include "event_filter.html" %}
                    </td>
                </tr>
            </thead>
            <tbody>
                {% for choreography in choreographies_qs %}
                    <tr>
                        <td>{{ choreography.pk }}</td>
                        <td colspan="2">
                            <a href="{{ choreography.get_absolute_url }}" class="text-decoration-none">
                                {{ choreography.name }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row justify-content-center gx-2 pt-2">
        {% include "go_back_button.html" %}
        {% include "update_button.html" %}
    </div>

{% endblock card_body %}

academy/templates/academy/dancer_form.html
{% extends "card.html" %}
{% load static widget_tweaks i18n %}

{% block card_body %}

    {% with WIDGET_ERROR_CLASS="is-invalid" %}
        <form method="post" autocomplete="off" novalidate id="dancer_form" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="row gx-2">
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.first_name.label_tag }}</span>
                        {% render_field form.first_name class="form-control rounded-end" %}
                        <div class="invalid-feedback">
                            {{ form.first_name.errors|first }}
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.last_name.label_tag }}</span>
                        {% render_field form.last_name class="form-control rounded-end" %}
                        <div class="invalid-feedback">
                            {{ form.last_name.errors|first }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row gx-2">
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.birth_date.label_tag }}</span>
                        {% render_field form.birth_date %}
                        <div class="invalid-feedback">
                            {{ form.birth_date.errors|first }}
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.identification_type.label_tag }}</span>
                        {% render_field form.identification_type class="form-select rounded-end" %}
                        <div class="invalid-feedback">
                            {{ form.identification_type.errors|first }}
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.identification_number.label_tag }}</span>
                        {% render_field form.identification_number class="form-control rounded-end" %}
                        <div class="invalid-feedback">
                            {{ form.identification_number.errors|first }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row gx-2">
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.identification_front_image.label_tag }}</span>
                        {% for field in form.identification_front_image %}
                            {% if field.data.value %}
                                <span class="form-control">
                                    <a href="{{ object.identification_front_image.url }}" class="text-decoration-none">{{ object.id_front_image_name }}</a>
                                </span>
                                <div class="input-group-text rounded-end">
                                    <input type="checkbox" name="identification_front_image-clear" id="identification_front_image-clear_id" class="form-check-input my-auto">
                                    <label for="identification_front_image-clear_id" class="ms-2">{% translate "Delete" %}</label>
                                </div>
                            {% else %}
                                {% render_field form.identification_front_image class="form-control rounded-end" %}
                            {% endif %}
                        {% endfor %}
                        <div class="invalid-feedback">
                            {{ form.identification_front_image.errors|first }}
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="input-group pb-2">
                        <span class="input-group-text">{{ form.identification_back_image.label_tag }}</span>
                        {% for field in form.identification_back_image %}
                            {% if field.data.value %}
                                <span class="form-control">
                                    <a href="{{ object.identification_back_image.url }}" class="text-decoration-none">{{ object.id_back_image_name }}</a>
                                </span>
                                <div class="input-group-text rounded-end">
                                    <input type="checkbox" name="identification_back_image-clear" id="identification_back_image-clear_id" class="form-check-input my-auto">
                                    <label for="identification_back_image-clear_id" class="ms-2">{% translate "Delete" %}</label>
                                </div>
                            {% else %}
                                {% render_field form.identification_back_image class="form-control rounded-end" %}
                            {% endif %}
                        {% endfor %}
                        <div class="invalid-feedback">
                            {{ form.identification_back_image.errors|first }}
                        </div>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center gx-2 pt-2">
                {% include "go_back_button.html" %}
                {% include "save_button.html" %}
            </div>
        </form>
    {% endwith %}

{% endblock card_body %}

academy/templates/academy/professor_detail.html
{% extends "card.html" %}
{% load static i18n %}

{% block card_body %}

    <div class="row gx-2">
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "First name" %}</span>
                <span class="form-control">{{ object.first_name }}</span>
            </div>
        </div>
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Last name" %}</span>
                <span class="form-control">{{ object.last_name }}</span>
            </div>
        </div>
    </div>

    <div class="row gx-2">
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Identification type" %}</span>
                <span class="form-control">{{ object.get_identification_type_display }}</span>
            </div>
        </div>
        <div class="col-sm">
            <div class="input-group pb-2">
                <span class="input-group-text">{% translate "Identification number" %}</span>
                <span class="form-control">{{ object.identification_number }}</span>
            </div>
        </div>
    </div>

    <div class="row gx-2 mb-2">
        <div class="col-sm">
            <p class="my-2">{% translate "Identification front image" %}</p>
            {% if object.identification_front_image %}
                <img src="{{ object.identification_front_image.url }}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% else %}
                <img src="{% static 'academy/images/id_card_front.svg' %}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% endif %}
        </div>
        <div class="col-sm">
            <p class="my-2">{% translate "Identification back image" %}</p>
            {% if object.identification_back_image %}
                <img src="{{ object.identification_back_image.url }}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% else %}
                <img src="{% static 'academy/images/id_card_back.svg' %}" class="img-fluid rounded mx-auto d-block" height="250" width="400" alt="">
            {% endif %}
        </div>
    </div>

    <div class="table-responsive mt-4">
        <table class="table table-striped align-middle text-center">
            <thead>
                <tr class="dark">
                    <td scope="col" class="align-middle">ID</td>
                    <td scope="col" class="align-middle">{% translate "Choreography name" %}</td>
                    <td scope="col" style="width: 30%;">
                        {% include "event_filter.html" %}
                    </td>
                </tr>
            </thead>
            <tbody>
                {% for choreography in choreographies_qs %}
                    <tr>
                        <td>{{ choreography.pk }}</td>
                        <td colspan="2">
                            <a href="{{ choreography.get_absolute_url }}" class="text-decoration-none">
                                {{ choreography.name }}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="row justify-content-center gx-2 pt-2">
        {% include "go_back_button.html" %}
        {% include "update_button.html" %}
    </div>

{% endblock card_body %}